MODEL:
  ANCHOR_GENERATOR:
    ANGLES: [[-90, 0, 90]]
    ASPECT_RATIOS: [[1.0, 0.5, 0.25]] # H/W
    NAME: DefaultAnchorGenerator
    OFFSET: 0.0
    SIZES: [[32, 64, 128, 256, 512]]
  META_ARCHITECTURE: "Detr"
  WEIGHTS: "converted_model.pth" #"detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  DETR:
    DEC_LAYERS: 6 #important
    DEEP_SUPERVISION: True #important | loss after each decoder layer
    DIM_FEEDFORWARD: 2048
    DROPOUT: 0.1
    ENC_LAYERS: 6 #important
    GIOU_WEIGHT: 2.0 #important
    HIDDEN_DIM: 256
    L1_WEIGHT: 5.0 #important
    NHEADS: 8
    NO_OBJECT_WEIGHT: 0.1 #important
    NUM_CLASSES: 12
    NUM_OBJECT_QUERIES: 300 #important
    PRE_NORM: False #can tweak this
  ROI_HEADS:
    NUM_CLASSES: 12
    BATCH_SIZE_PER_IMAGE: 64
DATASETS:
  TRAIN: ("my_dataset_train",)
  TEST: ("my_dataset_val",)
OUTPUT_DIR: "./output"
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  GAMMA: 0.1
  STEPS: (5000,)
  MAX_ITER: 10000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1 #important
  CLIP_GRADIENTS:
    ENABLED: False
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
INPUT:
  MIN_SIZE_TRAIN: (800,) # Size of the smallest side of the image during training
  CROP:
    ENABLED: False
    TYPE: "relative_range"
    SIZE: (0.9, 0.9)
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 500
  
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 4
VERSION: 2
